### ISSUE TITLE
Test details of S3 consistency

### ISSUE THREAD

**Issue by cket** [BD2KGenomics/slugflow#131]
Related to issue #121

**Comment by cket** [comment]
This team did something similar:
https://github.com/andrewgaul/are-we-consistent-yet
They have observed that in our region, they only observed 1 read after delete out of 100,000 operations, which I'm not sure I can verify. 

However, there is more discussion here:
http://www.infoq.com/news/2015/01/emrfs-s3-consistency
which points in the opposite direction, and even warns not to trust any the 'read-after-write' guarantee. 

I will do more research, but it looks like we should probably not count on anything except eventual consistency.

**Comment by hannes-ucsc** [comment]
Having read the material you cited here, I'm inclined to punt this one. I am certain that we will not read stale versions since we are using versioning. At worst we will get a "version does not exist error " which will fail the jobTree. But since we don't know what the exact error codes are, we can't write code to handle them.
