### ISSUE TITLE
Evaluate Luigi (2/2)

### ISSUE THREAD

**Issue by jvivian** [BD2KGenomics/slugflow#17]

**Comment by benedictpaten** [comment]
Like make, but uses python. 
Nice interface - can run any "task", and, like make, the appropriate dependencies will be run.
Is static - no dynamic task scheduling during execution - rather designed to work with Hadoop to do heavy lifting.
Unclear how well is supports generic clusters - seems to fit working with hadoop better.
Not sure about AWS support in general.

**Comment by jvivian** [comment]
I could only find one example of Luigi being used with AWS, but they simply made "tasks" things like download from S3, etc.  Nothing about dynamic or elastic instance creation and no mention of spot pricing.   The creator of Luigi  left spotify to work at a startup so while AWS support may be a "future consideration"  it's not something I'd expect anytime soon.

**Comment by benedictpaten** [comment]
What's your current favorite system, John?

My feeling is that Luigi and Seqware are too big (the ones I evaluated),
and will take us too much time to adapt - but I'm not the one learning the
code. Luigi definitely has the nicer interface.

I'm currently in favour of combining Hannes/your plan for creating a series
of AWS instance queue types, and getting jobTree to feed these queues.
However, that's because I understand the proposed system and can clearly
foresee the code to be written.

**Comment by jvivian** [comment]
I liked a lot of things about MakeFlow (and may find uses for it in the future) but it is not well supported, documented, and seems to be collecting a bit of dust.   Luigi seems great for static clusters/Hadoop jobs but that's not what we're shooting for.    CJ has been looking at Mesos and found some support for AWS, but I'm not sure how complete it is. Since I am unfamiliar with JobTree (and the other systems) my  personal vote would be writing it ourselves (both as a challenging learning experience and for the control it woudl leverage us), but I doubt that route will garner enough popularity to be the chosen path. 

I have an inkling Hannes is leaning strongly towards JobTree so I will spend some time looking at the code for tomorrow's meeting.

**Comment by benedictpaten** [comment]
There may be no absolutely wrong answer here - just a choice to be made.

I can see the bits of code we need to write for jobTree - because I wrote
it - not because it's the best or well documented. The interesting bit is
still to be written - the code management of clusters of AWS instances. In
this sense we are starting fresh - though the bit of code we have to write
is relatively small.

If we got this path, because it is so small, we can probably refactor most
of JobTree and improve the interface/installation/documentation to make it
more usable. The dependency on sonLib, for example, is silly.

**Comment by diekhans** [comment]
Note that Luigi is tiny compared to Taverna or SeqWare..

However, jobTree is well understood and getting it working in
AWS could be a huge tactical advantage to the CGL ...

**Comment by diekhans** [comment]
My reading is it doesn't have to use Hadoop, could easily use
spark (I think there is an example); but it's optimized for it
[meaning might not even work without it, but we designed for
it].

In concept, I am partial to at two layered approach:  dependency
manager and compute manager.

So my current second choice is to use Luigi on top of clusterx
on AWS and Mesos in NCI cluster.  Actually prototyping would
be require.

Current first choice would be JobTree on top of clusterx
and Mesos.

**Comment by benedictpaten** [comment]
I agree that testing Luigi would be good. I think it's pretty neat. I'm not
sure we'll use its bells and whistles - but I agree the potential
integration with Spark is a plus. You can imagine using CG-cloud to bring
up the cluster for Spark, then getting Luigi to drive the inputs and
outputs to Adam in some larger workflow.

**Comment by fnothaft** [comment]
We do a bit of that already: https://github.com/bigdatagenomics/eggo/blob/master/eggo/dag.py
Not taking full advantage of Luigi, but still.
