### ISSUE TITLE
Implement CWL->jobTree Graph (1 of 3)

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/slugflow#43]

**Comment by jvivian** [comment]
Current release of cwltool is broken (pip install cwltool). 

I had to explicitly add the .yml file from their github to the site-packages dir. 

**IOError: [Errno 2] No such file or directory: '/Users/Jvivian/anaconda/lib/python2.7/site-packages/cwltool/schemas/draft-2/cwl-avro.yml'**

Even after fixing that I haven't been able to get any of the examples I tried to work. 

Errors I got:

**Tool definition failed validation:
While validating requirements `ScatterFeature`
  Unknown requirement `ScatterFeature`**

**While validating hints DockerRequirement
  could not validate field `dockerImageId` because
    missing required field `dockerImageId`**

To replicate:

    pip install cwltool
    git clone https://github.com/common-workflow-language/common-workflow-language
    cd common-workflow-language/conformance/draft-2/
    cwltool <any workflow> <any job.json>

Since the pip release is behind  their github, I cloned the github and tried to install cwltool per instruction:
   
    cd common-workflow-language/reference
    easy_install . 

This did not work and I had to force-quit to exit the installation. 

Should I open a github issue?  Should we just wait to deal with CWL until they have a working release?

**Comment by hannes-ucsc** [comment]
The whole project is fragmented, inconsistent and badly documented. They don't have comprehensive examples, most of their examples are really just unit test.

Having said that, I got the bwa-mem workflow to parse and actually run a command. The command uses docker which I don't have installed anymore but this tells me that the basics are working.

```
git clone https://github.com/common-workflow-language/common-workflow-language
cd common-workflow-language/
virtualenv venv
cd reference/
../venv/bin/python setup.py install
cd ../conformance/draft-2/
../../venv/bin/python ../../reference/cwltool/main.py bwa-mem-tool.cwl bwa-mem-job.json 
```

**Comment by hannes-ucsc** [comment]
Note that I now basically use a virtualenv for everything in Python.

**Comment by jvivian** [comment]
Thanks Hannes, I should have realized there was an alternate installation method via the setup.py.  Even after installing cwltools through that method I am still unable to get any of the examples working.

Most of the docker images return "image not found", or they fail the subprocess call to pull the image,  or they are missing dependencies needed to run the workflow.

**Comment by hannes-ucsc** [comment]
Cancelled
