### ISSUE TITLE
Write AbstractBatchSystemTest

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/slugflow#59]

**Comment by hannes-ucsc** [comment]
Well done, John. I can't think of much more that could be tested but I add a few minor FIXME/TODOs. Try to fix the quick ones but then go ahead and close this issue. 

I reduced the number of empty lines because I think it increases readability.

We should from now on always use the logging package instead of the print statement for   diagnostic output.  I already did that in this test case.

**Comment by hannes-ucsc** [comment]
Looks complete to me. John, can you confirm?

**Comment by jvivian** [comment]
one of the tests unexpectedly failed when I ran it on the plane (mesos testIssueJob) and I need to clean up another one (getUpdatedJob).  I will close this when I fix them.

**Comment by jvivian** [comment]
Closing.  The unexpected failure was due to the MesosBatchSystem.
To replicate error run unittests in MesosBatchSystemTest.   

To test with singleMachine (not finished yet, so this is hacky):

1. Replace line 56 (**self.wait_for_jobs**) with **time.sleep(5)**
2. Run **getIssueJob** (you can use Hannes's workaround to just run a single test) with *SingleMachineBatchSystemTest*, which should pass.   
3. Then run it again with *MesosBatchSystemTest* and it will fail.     

Mesos used to pass all these tests so I'm going to open a separate ticket for this and look into the commit history to see what may have changed.

**Comment by hannes-ucsc** [comment]
> not finished yet

How do we keep track of that? Is there another issue about it?

**Comment by jvivian** [comment]
> How do we keep track of that? Is there another issue about it?

There is a ticket (assigned to me) to finish implementing the singleMachine methods.  

We talked about this at one point, but I think it's worth reconsidering having a separate .py file for each batch system -- that way a test can be run by selecting the file and running the unittest as opposed to going into the AbstractBatchSystemTest and selecting a class to run or editing the configuration to point to a specific class.

**Comment by hannes-ucsc** [comment]
Roger that.

On Mon, Jun 1, 2015 at 12:43 PM, John Vivian <notifications@github.com>
wrote:

> How do we keep track of that? Is there another issue about it?
>
> There is a ticket (assigned to me) to finish implementing the
> singleMachine methods.
>
> We talked about this at one point, but I think it's worth reconsidering
> having a separate .py file for each batch system -- that way a test can be
> run by selecting the file and running the unittest as opposed to going into
> the AbstractBatchSystemTest and selecting a class to run or editing the
> configuration to point to a specific class.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BD2KGenomics/slugflow/issues/59#issuecomment-107681557>
> .
>



-- 
Hannes Schmidt
Software Engineer
Center for Biomolecular Science and Engineering
University of California, Santa Cruz

(206) 696-2316 (cell)
hannes@ucsc.edu
