### ISSUE TITLE
Finish threads, queues and processes excercise assignment

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/slugflow#6]

**Comment by jvivian** [comment]
"Have another thread prompting the user for numbers and feeding the responses into the queue. Think about how to terminate all threads cleanly"
https://github.com/jvivian/10k_exome_project/blob/master/Code/mptest_3.py

A common bug that I dealt with was that you need to leave the parentheses off when assigning a function as the target of a thread. 

In this case I used the "sentinel" method we talked about to end the program at the user's behest, while maintaining the ability to run N jobs. 

I didn't make use of thread.join here, which indicates to me I did something incorrect / inelegant (most likely the use of os_exit), but I figured that the it would be a feature for the job thread to hang when there are no more items in the queue, then resume immediately upon the entry of a new number by the user. 

Not that it matters, but there didn't seem to be an easy way to avoid the the output from the job thread overrunning the raw_input request on screen. I piped away the stderr from the subprocess call to make it a little more legible.

**Comment by hannes-ucsc** [comment]
There's no way around Thread.join() for a clean exit. sys.exit should only be used in response to exceptional conditions, not the normal flow of a program.

The queue items should be integers. User input should be validated early and then converted to more specific and richer types. User-provided strings should not leech into the system too deeply.

With user input, there is no need to populate the queue anymore.

**Comment by jvivian** [comment]
Hey Hannes, 

CJ and I worked on the problem together and we tried to address all of your points.  Let us know if we can improve anything.  https://github.com/jvivian/10k_exome_project/blob/master/Code/mptest_3.py

**Comment by hannes-ucsc** [comment]
Entering S does not quit the program. I have to enter it twice. 

The handler's while condition is a little convoluted. If any string terminates the loop, then why test for "S"?  I recommend using None or -1 as the sentinel. And instead of S followed by Enter, I would trigger the exit code path if the user does not enter anything, just hits Enter. But that's not so important.

The catch-all except statement should be more specific, if it is needed at all. You don't want to catch any exception, just the one you are expecting, which is ValueError, I believe.

You should not use PIPE with subprocess.call(). See https://docs.python.org/2/library/subprocess.html#using-the-subprocess-module

Use check_call() instead of call().

For bonus points, but not trivial: Ctrl-C currently does nothing. Try to make it exit the program immediately.

More bonus points: If an exception occurs in a handler, make the program exit immediately.

**Comment by jvivian** [comment]
When we discussed sentinels I thought the idea was that each thread would receive it's own sentinel before shutting down -- in this case it was intentional that sending one sentinel would shut down one thread, allowing the other thread to continue working until it receives one as well.   In this case, I've changed the code so that "Enter" will signal the closure of all threads (letting ones that are working finish) and that entering a "-1" will close one thread at a time. 

Fixed.

I used it to remove clutter from the screen, but I've reverted.

Fixed.

I tried to implement this (if you look at the commented code), but couldn't get the class "Worker" to work with the the KeyboardInterrupt except statement, it seemed that t.join() wasn't blocking so the program exited immediately.  I was using [this site](http://www.regexprn.com/2010/05/killing-multithreaded-python-programs.html) as a reference.

If an exception occurs in the process of calling a handler the program exits immediately.

**Comment by hannes-ucsc** [comment]
In a real world program I would separate the user input and error checking into a separate function. That function should print an error message on invalid input, but otherwise ignore the input. It should not exit the program! The q.put(int(val)) is what irks me because it combines input validation logic with queueing logic. Those should be separate.

Anyways, good work. Closing the issue.
